name: CI

on: [ push ]

# on:
#   push:
#     branches:
#       - master
#       - develop
#   pull_request:
#     branches:
#       - master
#       - develop

# jobs:
#   build:
#     runs-on: ubuntu-latest
#
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
#       - name: Build with Gradle
#         run: ./gradlew build

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
      #  with: openjdk@1.14
      - name: Login
        run: docker login https://ghcr.io -u token --password-stdin <<< ${{ secrets.GHCR_TOKEN }}
      - name: Compile, build and publish Docker Image
        run: |
          sbt compile docker:publishLocal && \
          docker tag pinkstack/voda:latest ghcr.io/pinkstack/voda && \
          docker push ghcr.io/pinkstack/voda
