name: CI

on: [push]

# on:
#   push:
#     branches:
#       - master
#       - develop
#   pull_request:
#     branches:
#       - master
#       - develop

# jobs:
#   build:
#     runs-on: ubuntu-latest
#
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
#       - name: Build with Gradle
#         run: ./gradlew build

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with: openjdk@1.14
      - name: Login in docker.pkg.github.com
        run: docker login -u ${GITHUB_ACTOR} -p ${{secrets.GITHUB_TOKEN}} docker.pkg.github.com
      - name: Compile and build Docker Image
        run: sbt compile docker:publishLocal
      - name: Push to GitHub Packages
        run: |
          docker tag pinkstack/voda docker.pkg.github.com/pinkstack/voda/voda && \
          docker push docker.pkg.github.com/pinkstack/voda/voda